/*
 * Created Date: Tuesday April 2nd 2019
 * Last Modified: Tuesday April 2nd 2019 11:00:02 pm
 * Author: ankurrc
 */
# Site settings
title: Main
description: Ankur's Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ankur Roy Chowdhury
user_description: I am a Master's student in Computer Science at Texas A&M University. In the past, I've worked as a full-stack developer on the Internet of Things. The last couple of years, I've been involved with autonomous robots. Currently, my interests include solving perception problems in mobile robots.
user_title: MS Student in Computer Science
email: ankurrc.academia@gmail.com
twitter_username: ankur_rc
github_username:  ankur-rc
linkedin_username: ankur-roy-chowdhury
stackoverflow_uname: ankurrc

# Google-analytics
google-analytics:
  id: "UA-137603716-1"

exclude: ['package.json', 'src' , 'node_modules']
