# Site settings
title: Main
description: Ankur's Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ankur Roy Chowdhury
user_description: 
user_title: Software Developer
email: ankurrc.academia@gmail.com
twitter_username: ankur_rc
github_username:  ankur-rc
linkedin_username: ankur-roy-chowdhury
stackoverflow_uname: ankurrc

# Google-analytics
google-analytics:
  id: "UA-137603716-1"

exclude: ['package.json', 'src' , 'node_modules']
